//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito_4am.Seguridad
{
    public partial class CrudProveedor
    {
        /// <summary>
        /// hfProveedorID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfProveedorID;

        /// <summary>
        /// txtNombreProv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombreProv;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// btnCancelar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>
        /// gvProveedores control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProveedores;
    }
}
